version: "3.9"

services:
  obs:
    image: gowatch:latest
    container_name: gowatch
    build:
      context: ./
      dockerfile: .setup/build/Dockerfile
    volumes:
      - ./:/go/src
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TERM=xterm
    stdin_open: true
    tty: true
